steps:
  # Setup/verify secrets from environment (for CI/CD)
  # Note: In CI/CD, secrets should be set as Cloud Build substitution variables or environment
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔐 Setting up Cloud Secrets for CI/CD deployment..."
        # For CI/CD, we assume secrets are already configured or will be set via substitution variables
        # This step verifies existing secrets are accessible
        gcloud secrets versions access latest --secret="neemee-github-token" >/dev/null || echo "⚠️ neemee-github-token not found"
        gcloud secrets versions access latest --secret="neemee-supabase-url" >/dev/null || echo "⚠️ neemee-supabase-url not found"
        gcloud secrets versions access latest --secret="neemee-supabase-anon-key" >/dev/null || echo "⚠️ neemee-supabase-anon-key not found"
        gcloud secrets versions access latest --secret="neemee-github-repo-owner" >/dev/null || echo "⚠️ neemee-github-repo-owner not found"
        gcloud secrets versions access latest --secret="neemee-github-repo-name" >/dev/null || echo "⚠️ neemee-github-repo-name not found"
        echo "✅ Secrets verification complete"
    id: 'Setup-Secrets'

  # Deploy using Cloud Run source deployment (buildpacks)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'neemee-frontend'
      - '--source=.'
      - '--platform=managed'
      - '--region=us-central1'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=100'
      - '--concurrency=80'
      - '--timeout=300'
      - '--allow-unauthenticated'
      # Mount secrets as environment variables
      - '--set-secrets=GITHUB_TOKEN=neemee-github-token:latest'
      - '--set-secrets=NEXT_PUBLIC_SUPABASE_URL=neemee-supabase-url:latest'
      - '--set-secrets=NEXT_PUBLIC_SUPABASE_ANON_KEY=neemee-supabase-anon-key:latest'
      - '--set-secrets=GITHUB_REPO_OWNER=neemee-github-repo-owner:latest'
      - '--set-secrets=GITHUB_REPO_NAME=neemee-github-repo-name:latest'
      # Set environment variables
      - '--set-env-vars=NODE_ENV=production,VERSION=$COMMIT_SHA'
      - '--labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,service=neemee-frontend'
      - '--quiet'
    id: 'Deploy'

# Note: No separate image build step needed - Cloud Run source deployment handles everything

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # Use faster machine for build

# Required IAM permissions for Cloud Build service account:
# - Cloud Run Admin
# - Secret Manager Secret Accessor
# - Artifact Registry Writer
# - Service Account User

tags:
  - 'gcp-cloud-build-deploy-cloud-run'
  - 'gcp-cloud-build-deploy-cloud-run-managed'
  - 'neemee-frontend'